version: '3.9'

services:
  web:
    build: .
    image: hometime_api:latest
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    command: bash -c "rake assets:precompile && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - postgres
      - redis
      - sidekiq
    ports:
      - 3000:3000

  sidekiq:
    image: hometime_api:latest
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  bundler_gems:
