version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    environment:
      RAILS_ENV: development
    command: bash -c "rake assets:precompile && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  bundler_gems:
